config/routes.rb
Rails.application.routes.draw do

  #routes for all visitors
  get '/', to: 'core#home'

  # routes for UW students

  get '/uw/home', to: 'waterloo_core#home'
  get '/uw/about', to: 'waterloo_core#about'
  get '/uw/constitution', to: 'waterloo_core#constitution'

  # routes for WLU students

  get '/wlu/home', to: 'laurier_core#home'
  get '/wlu/constitution', to: 'laurier_core#constitution'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
  def home
    render "home"
  end
end

app/controllers/core_controller_controller.rb
class CoreControllerController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def constitution
  end
end

app/controllers/laurier_core_controller.rb
class LaurierCoreController < ApplicationController
  def home
    render "home"
  end

  def constitution
    render "constitution"
  end
end

app/controllers/waterloo_core_controller.rb
class WaterlooCoreController < ApplicationController
  def home
    render "home"
  end

  def about
    render "about"
  end

  def constitution
    render "constitution"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/core_controller_helper.rb
module CoreControllerHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/laurier_core_helper.rb
module LaurierCoreHelper
end

app/helpers/waterloo_core_helper.rb
module WaterlooCoreHelper
end

app/views/core/home.html.erb
<div id="core-container">
  <header>
    <h1>Welcome to Kitchener-Waterloo's collection of Serbian student associations</h1>
    <h2>Choose a university</h2>
  </header>

  <article id="core">
    <a href="/wlu/home">
      <section id="laurier-section">
        <img src="laurier.png" alt="Logo for the laurier side.">
      </section>
    </a>

    <a href="/uw/home">
      <section id="waterloo-section">
        <img src="waterloo.png" alt="Logo for the waterloo side.">
      </section>
    </a>

  </article>
</div>

app/views/core_controller/about.html.erb
<h1>CoreController#about</h1>
<p>Find me in app/views/core_controller/about.html.erb</p>

app/views/core_controller/constitution.html.erb
<h1>CoreController#constitution</h1>
<p>Find me in app/views/core_controller/constitution.html.erb</p>

app/views/core_controller/contact.html.erb
<h1>CoreController#contact</h1>
<p>Find me in app/views/core_controller/contact.html.erb</p>

app/views/core_controller/home.html.erb
<h1>Currently in construction...come back soon!</h1>

app/views/laurier_core/_header.html.erb
<header id="wlu-header">
  <img src="/wlu-text.png" alt="WLUSSA as text">
  <nav id="laurier-nav">
    <ul>
      <li><%= link_to "Home", wlu_home_path %></li>
      <li><%= link_to "Constitution", wlu_constitution_path %></li>
      <li>
        <a href="mailto:wluserbian@gmail.com">
          <i class="fa fa-envelope" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/wluserbianstudentassociation/">
          <i class="fa fa-facebook-square" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="https://www.twitter.com/wluserbassoc">
          <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
      </li>
      <li><%= link_to "UWaterloo SSA", uw_home_path %></li>
    </ul>
  </nav>
  <img src="/wlu-club-logo.png" alt="The club and associations logo.">
</header>

app/views/laurier_core/constitution.html.erb
<%= render "header" %>

<article id="wlu-body">
  <img src="/purpleserbianeagle.png" alt="the club's logo as the background">
  <h1>The Constitution</h1>
  <section class="section-wlu">
    <h2>Name</h2>
    <p>The club’s official name will be “WLU Serbian Student Association”.  The
      abbreviation will be “WLUSSA”. No other names will be used in the advertisement
      or representation of the club.</p>

    <h2>Purpose of Club</h2>
    <ul>
      <li>To provide a channel of communication between WLU students of Serbian
        background as well as anyone else interested in Serbian culture and tradition.</li>
      <li>To provide new WLU students of Serbian background with academic and
        non-academic forms of help and assist them with engaging in university activities.</li>
      <li>To initiate and support academic, social and athletic activities
        within Wilfrid Laurier University.</li>
      <li>To promote respect and mutual understanding within the multicultural
        environment of WLU.</li></ul>

    <h2>Membership</h2>
    <ul>
      <li>Membership is open to all undergraduate and graduate students at WLU.</li>
      <li>Only undergraduate and graduate students at WLU are eligible to hold
        voting privileges and executive positions</li>
      <li>Voting membership will be open to all undergraduate and graduate students
        of Wilfrid Laurier University, both registered and on work-term. Associate
        membership is open to alumni, faculty and staff members.</li></ul>

    <h2>Executive</h2>
    <p>The executive committee shall consist of:</p>
    <ol type="a">
      <li>President</li>
      <li>Vice President</li>
      <li>Finance Executive</li>
      <li>Event Coordinator</li>
      <li>Communications Coordinator</li>
      <li>Treasurer</li>
      <li>Secretary</li>
    </ol>
    <p>*Or as otherwise determined by the President</p>

    <h2>Duties of the Executive Committee</h2>
    <p>1. President</p>
    <p>Ensure events are held, promote the club, create an agenda and act as the
      chair over the club meetings. The President shall, with the assistance of
      the Vice-President, be responsible for all Club/Faculty relations, Club/Student
      relations and most importantly relations with the WLU Students’ Union.</p>
    <p>2. Vice President</p>
    <p>Assist the president in all duties, to act as one of the two signing authorities,
      to ensure that all club activities and promotions conform to the club’s policies,
      and take over president’s role in president’s absence. The Vice-President shall,
      with the assistance of the President, be responsible for all Club/Faculty relations,
      Club/Student relations and most importantly relations with the WLU Students’ Union.</p>
    <p>3. Finance Executive</p>
    <p>Responsible for the financial matters of the club (in correspondence with
      the WLU Students’ Union); in particular, act as one of the two signing authorities,
      and maintain an accurate record of all financial transactions.</p>
    <p>4. Event Coordinator</p>
    <p>Duties are to oversee and guide organization of all of the club events.</p>
    <p>5. Communications Coordinator</p>
    <p>Duties are to guide the formation of promotional material for the club events.
      In addition, the duties include organization of on-line communications of the club
      members; specifically, maintenance of the club’s email list, and distribution of
      the club’s announcements.</p>
    <p>6. Treasurer</p>
    <p>Assist with the financial matters of the club; in particular, aid the
      Finance Executive in maintaining an accurate record of all financial transactions
    <p>7. Secretary</p>
    <p>Ensure that clear and precise minutes are kept from all of the club meetings,
      if decided on doing so prior to the meeting. Act as a medium of communication
      between all other club executives and general members.</p>

    <h2>Finances</h2>
    <p>Reimbursement forms and receipts will be collected after every event that
      requires any sort of expense. Such events will first be brought to the attention
      of the WLU Students’ Union to seek approval, and will only go forth if approval
      is granted. Collecting these forms will be the responsibility of the executive
      committee, namely the Finance Executive. Expenses will be approved only if the
      WLU Student’s Union gives approval, and will be brought to the Union by the
      executive committee, namely the President and Vice President.</p>

    <h2>Meetings</h2>
    <ul>
      <li>At least one general meeting must be held per term</li>
      <li>Members will be informed of these meetings at least 7 days in advance.
        Meetings will be aimed to be held at least once every second week</li>
    </ul>

    <h2>Succession</h2>
    <p>The succeeding President, Vice President, Finance Executive and other
      desired Executive members will be appointed by the current President in
      their last term at WLU.</p>

    <h2>Amendments</h2>
    <ul>
      <li>Amendments to the constitution must be both passed with two-thirds (2/3)
      majority with half (1/2) of the voting members present, and approved by the President</li>
      <li>Amendments to the constitution must be approved by the VP: Clubs and Associations</li>
      <li>Any full member can submit a proposal for an amendment to the constitution at any general meeting</li>
    </ul>

    <h2>Removal of Members and Executive</h2>
    <p>A club executive/member may be automatically removed under the following
      conditions, if approved by the President:</p>
    <ol type="a">
      <li>Theft, fraud and/or embezzlement of funds</li>
      <li>Behavior inconsistent with the Code of Conduct of Students as described
        in the University Undergraduate Calendar</li>
      <li>Inappropriate behaviour or actions in relation to their position in the Club</li>
    </ol>
    <p>If a club executive/member breaches Club policy by acting in a manner
      that is not consistent with upholding the dignity of the constitution or
      chooses to misrepresent the Club by acting in ways that degrade fellow
      Club members or WLU students, staff, faculty, as well as any other public
      citizens, they may be brought to the attention of the President who will make
      the decision to remove, or warn the party.</p>
  </section>
</article>

app/views/laurier_core/home.html.erb
<%= render "header" %>

<article id="wlu-body">
  <img src="/purpleserbianeagle.png" alt="the club's logo as the background">
  <h1>Welcome to the Wilfrid Laurier University Serbian Student Association!</h1>
  <div id="wlu-feeds-main-container">
    <section class="news-feed wlu-news-feed">
      <h2>News</h2>
      <article class="post wlu-post">
        <div class="post-intro wlu-post-intro">
          <h3>General Meeting on Thursday</h3>
          <h3>September 27, 2017</h3>
        </div>
        <div class="post-body wlu-post-body">
          <p>Hi guys, the Serbian club will have their first general meeting in
             the back lounge at Wilf's around 2:30 pm. We would love to have everyone
             get to know each other, enjoy some snacks and learn about the exciting things
             we have planned for this term!</p>
        </div>
        <div class="post-footer wlu-post-footer">
          <p>Nikola Miokovic, Club President</p>
        </div>
      </article>
      <article class="post wlu-post">
        <div class="post-intro wlu-post-intro">
          <h3>Greetings!</h3>
          <h3>September 14, 2017</h3>
        </div>
        <div class="post-body wlu-post-body">
          <p>Welcome to the Wilfrid Laurier University Serbian Club's website! Here you
             will find lots of information on meetings, events, club members,
             special offers and more! We look forward to a great year with everyone!</p>
        </div>
        <div class="post-footer wlu-post-footer">
          <p>Ilija Milisav, Lead Web Developer</p>
        </div>
      </article>
    </section>

    <aside class="event-feed wlu-event-feed">
      <div id="event-feed-events">
        <h2>Upcoming Events</h2>
        <article class="event wlu-event">
          <p>No upcoming events</p>
        </article>
      </div>

      <div id="event-feed-mission">
        <h2>Our Mission</h2>
        <p>WLUSSA's mission is to promote the Serbian culture to the Wilfrid Laurier
           students, staff, faculty and members of the WLU community at large.</p>
        <p>We will do this by providing many opportunities for social interaction between
           the university community and the club such as social events, guest speakers,
           activities and/or initatives.</p>
        <p>The most important is to allow students to create strong, long-lasting friendships
           with people of similar interests.</p>
      </div>
    </aside>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Serbian Student Association</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <script src="https://use.fontawesome.com/e049e133af.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/waterloo_core/_header.html.erb
<header id="uw-header">
  <img src="/uw-text.png" alt="UWSSA text">
  <nav id="waterloo-nav">
    <ul>
      <li><%= link_to "Home", uw_home_path %></li>
      <li><%= link_to "About", uw_about_path %></li>
      <li><%= link_to "Constitution", uw_constitution_path %></li>
      <li><a href="https://www.gofundme.com/uw-serbian-student-association">Donate</a></li>
      <li>
        <a href="mailto:ssa@clubs.feds.ca">
          <i class="fa fa-envelope" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/groups/149628768878448/">
          <i class="fa fa-facebook-square" aria-hidden="true"></i>
        </a>
      </li>
      <li><%= link_to "Laurier SSA", wlu_home_path %></li>
    </ul>
  </nav>
  <img src="/fedslogo.png" alt="The University of Waterloo's federation of students logo.">
</header>

app/views/waterloo_core/about.html.erb
<%= render "header" %>
<article id="uw-body">
  <img src="/blackserbianeagle.png" alt="serbian coat of arms as the background">
  <h1>About The Executives</h1>

  <section class="description-uw">
    <h2>Milana Krajisnik, <small>Club President</small></h2>
    <p>Milana is the president of the club. She is going into her second year of
       honours science.</p>
    <ul>
      <li>She makes sure that the UWSSA operates
       according to the guidelines of the constitution</li>
      <li>She also makes sure that club meetings follow club guidelines</li>
      <li>She ensures that the club works towards its
      objectives as agreed upon by the general membership</li>
      <li>She informs members
      of the club of upcoming events and meeting/gatherings on social media</li>
    </ul>
  </section>

  <section class="description-uw">
    <h2>Simonida Gnjatic, <small>Club Co-President</small></h2>
    <p>Simonida is one of the co-presidents of the club. She is entering her
       third year in Honours Science. She works very closely with Milana to make
       sure everything runs smoothly, taking over some roles of the president if
       needed. A few fun facts about her: Her father is from Bijeljina, Bosnia and her mother is
       from Gornji Milanovac, Serbia. On her spare time she likes to travel,
       play scrabble and eat pasta!</p>
  </section>

  <section class="description-uw">
    <h2>Marijana Svrdlin, <small>Club Co-President</small></h2>
    <p>Marijana is the other co-president of the club. She works very closely with
       Simonida and Milana on club matters. Marijana is currently entering her
       second year into Honours Biochemistry. She will also be helping the AIESEC
       International Organization where anyone interested in a global volunteer/work
       experience can find great opportunities right in Serbia for the Winter/Spring.</p>
  </section>

  <section class="description-uw">
    <h2>Lana Boskovic, <small>Secretary</small></h2>
    <p>The Secretary ensures that:</p>
    <ul>
    	<li>Records of what the group has done are maintained, distributed, and are accessible to all the members</li>
    	<li>Meeting minutes/notes are recorded and made available to all voting members</li>
    	<li>All club correspondence is monitored and brought to the attention of the appropriate person(s)</li>
    	<li>The duties of the President are undertaken in his/her absence; and is a signing authority</li>
    </ul>
  </section>

  <section class="description-uw">
    <h2>Savo Krajisnik, <small>Treasurer</small></h2>
    <p>The Treasurer ensures that:</p>
    <ul>
    	<li>The club’s Feds bank account and all financial transactions for the club are monitored and verified</li>
    	<li>All club revenues are collected, deposited into the club’s Feds bank account, and reconciled correctly and within a timely manner</li>
    	<li>Club cheque requests are submitted correctly and in a timely manner; and is a signing authority</li>
    </ul>
  </section>

  <section class="description-uw">
    <h2>Jovan Lisulov, <small>Event Planner</small></h2>
    <p>Jovan is one of the few event planners in the club. He is in charge of:</p>
    <ul>
      <li>Organizing all events hosted by the club</li>
      <li>Making sure the events run as planned</li>
      <li>Book event locations and handle food &amp; entertainment for the events</li>
    </ul>
  </section>

  <section class="description-uw">
    <h2>Jovana Zubic, <small>Event Planner</small></h2>
    <p>Jovana works along with Jovan to organize events that will be hosted by the UWSSA. She is in her second year of Kinesiology.</p>
  </section>

  <section class="description-uw">
    <h2>Neda Jovanovic, <small>Event Planner</small></h2>
    <p>Neda works with the other two event planners with UWSSA event planning. She is also in her second year of Kinesiology.</p>
  </section>

  <section class="description-uw">
    <h2>Olivera Kralj, <small>Marketing</small></h2>
    <p>Olivera is the head of marketing for the club. She is in charge of:
    <ul>
      <li>Designing banners/posters</li>
      <li>Placing advertisements around the school when need be</li>
      <li>Also advertises on the club's website and the club's social media</li>
    </ul>
    <p>Olivera Kralj is a third year Life Physics co-op student specializing in
      medical physics and minoring in biology. She was born and raised Canadian
      with Serbian parents from Belgrade and is eager to help build and grow the
      UW Serbian student community. When she's not huddled in the library studying, she
      likes to spend her spare time drawing/painting, petting dogs and working
      out at the gym. She's always happy to meet new people so feel free to give
      her a wave if you see her on campus!</p>
  </section>

  <section class="description-uw">
    <h2>Ilija Milisav, <small>Lead Web Developer</small></h2>
    <p>Ilija is the lead developer of this site. He is responsible for:</p>
    <ul>
      <li>Maintaining the website to be up to standards with the student
          governing body (Feds) and with the World Wide Web Consortium.</li>
      <li>Helps out Olivera with various marketing tasks, when need be</li>
      <li>Communicates with Wilfrid Laurier's Serbian Student Club to maintain
        their website as well</li>
    </ul>
    <p>He is currently studying Computer Science at Laurier. If he's not busy
       with school or coding, he loves to go jogging, hang out with his
       friends and read.</p>
  </section>
</article>

app/views/waterloo_core/home.html.erb
<%= render "header" %>
<article id="uw-body">
  <img src="/blackserbianeagle.png" alt="serbian coat of arms as the background">
  <h1>Welcome to the University of Waterloo Serbian Student Association!</h1>
  <div id="uw-feeds-main-container">
    <section class="news-feed uw-news-feed">
      <h2>News</h2>
      <article class="post uw-post">
        <div class="post-intro uw-post-intro">
          <h3>Great News!!</h3>
          <h3>October 20, 2017</h3>
        </div>
        <div class="post-body uw-post-body">
            <p>The Embassy of the Republic of Serbia, in Ottawa, has some exciting news for us all.</p>
            <p>A Serbian Academic Network in Canada has officially started up!
                Becoming a member of this wonderful group will come with many
                benefits. Networking with other students, researchers, professors,
                doctors, and other professionals is a great opportunity for building
                connections. Ideally, the goal will be to unite the relationships within
                these groups between Canada and Serbia.</p>
            <p>Milan Tepic has been appointed the position of a secretary for
                the Serbian Academic Network in Canada and can be contacted
                through: serbiacademicnetcan@gmail.com Anybody willing to provide
                their email in effort to strengthen this network is kindly asked
                to send in an email expressing their interest in being a member.</p>
        </div>
        <div class="post-footer uw-post-footer">
          <p>Milana Krajisnik, Club President</p>
        </div>
      </article>

      <article class="post uw-post">
        <div class="post-intro uw-post-intro">
          <h3>Greetings!</h3>
          <h3>September 14, 2017</h3>
        </div>
        <div class="post-body uw-post-body">
          <p>Welcome to the University of Waterloo Serbian Club's website! Here you
             will find lots of information on meetings, events, club members,
             special offers and more! We look forward to a great year with everyone!</p>
        </div>
        <div class="post-footer uw-post-footer">
          <p>Ilija Milisav, Lead Web Developer</p>
        </div>
      </article>
    </section>

    <aside class="event-feed uw-event-feed">
      <div id="event-feed-events">
        <h2>Upcoming Events</h2>
        <article class="event uw-event">
          <p>No upcoming events</p>
        </article>
      </div>

      <div id="event-feed-mission">
        <h2>Our Mission</h2>
        <p>UWSSA's mission is to promote the Serbian culture to the University of
           Waterloo students, staff, faculty and members of the UW community at large.</p>
        <p>We will do this by providing many opportunities for social interaction between
           the university community and the club such as social events, guest speakers,
           activities and/or initatives.</p>
        <p>The most important is to allow students to create strong, long-lasting friendships
           with people of similar interests.</p>
      </div>
    </aside>
  </div>
</article>